/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiAssignmentStatus = {
    Open: 'open',
    Done: 'done',
    Blocked: 'blocked',
    Irrelevant: 'irrelevant'
} as const;
export type ApiAssignmentStatus = typeof ApiAssignmentStatus[keyof typeof ApiAssignmentStatus];


export function ApiAssignmentStatusFromJSON(json: any): ApiAssignmentStatus {
    return ApiAssignmentStatusFromJSONTyped(json, false);
}

export function ApiAssignmentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAssignmentStatus {
    return json as ApiAssignmentStatus;
}

export function ApiAssignmentStatusToJSON(value?: ApiAssignmentStatus | null): any {
    return value as any;
}

