/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiAssignmentType = {
    Task: 'task',
    ProblemSet: 'problemSet'
} as const;
export type ApiAssignmentType = typeof ApiAssignmentType[keyof typeof ApiAssignmentType];


export function ApiAssignmentTypeFromJSON(json: any): ApiAssignmentType {
    return ApiAssignmentTypeFromJSONTyped(json, false);
}

export function ApiAssignmentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAssignmentType {
    return json as ApiAssignmentType;
}

export function ApiAssignmentTypeToJSON(value?: ApiAssignmentType | null): any {
    return value as any;
}

