/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiFamilyTask } from './ApiFamilyTask';
import {
    ApiFamilyTaskFromJSON,
    ApiFamilyTaskFromJSONTyped,
    ApiFamilyTaskToJSON,
} from './ApiFamilyTask';

/**
 * 
 * @export
 * @interface ApiCreateFamilyTaskCommandArgs
 */
export interface ApiCreateFamilyTaskCommandArgs {
    /**
     * 
     * @type {ApiFamilyTask}
     * @memberof ApiCreateFamilyTaskCommandArgs
     */
    task: ApiFamilyTask;
}

/**
 * Check if a given object implements the ApiCreateFamilyTaskCommandArgs interface.
 */
export function instanceOfApiCreateFamilyTaskCommandArgs(value: object): boolean {
    if (!('task' in value)) return false;
    return true;
}

export function ApiCreateFamilyTaskCommandArgsFromJSON(json: any): ApiCreateFamilyTaskCommandArgs {
    return ApiCreateFamilyTaskCommandArgsFromJSONTyped(json, false);
}

export function ApiCreateFamilyTaskCommandArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCreateFamilyTaskCommandArgs {
    if (json == null) {
        return json;
    }
    return {
        
        'task': ApiFamilyTaskFromJSON(json['task']),
    };
}

export function ApiCreateFamilyTaskCommandArgsToJSON(value?: ApiCreateFamilyTaskCommandArgs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'task': ApiFamilyTaskToJSON(value['task']),
    };
}

