/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiCreateProblemSetCommandArgs
 */
export interface ApiCreateProblemSetCommandArgs {
    /**
     * 
     * @type {string}
     * @memberof ApiCreateProblemSetCommandArgs
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreateProblemSetCommandArgs
     */
    forUserId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreateProblemSetCommandArgs
     */
    description?: string;
}

/**
 * Check if a given object implements the ApiCreateProblemSetCommandArgs interface.
 */
export function instanceOfApiCreateProblemSetCommandArgs(value: object): boolean {
    if (!('title' in value)) return false;
    if (!('forUserId' in value)) return false;
    return true;
}

export function ApiCreateProblemSetCommandArgsFromJSON(json: any): ApiCreateProblemSetCommandArgs {
    return ApiCreateProblemSetCommandArgsFromJSONTyped(json, false);
}

export function ApiCreateProblemSetCommandArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCreateProblemSetCommandArgs {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'forUserId': json['forUserId'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ApiCreateProblemSetCommandArgsToJSON(value?: ApiCreateProblemSetCommandArgs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'forUserId': value['forUserId'],
        'description': value['description'],
    };
}

