/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDeleteFamilyTaskCommandArgs
 */
export interface ApiDeleteFamilyTaskCommandArgs {
    /**
     * 
     * @type {string}
     * @memberof ApiDeleteFamilyTaskCommandArgs
     */
    taskId: string;
}

/**
 * Check if a given object implements the ApiDeleteFamilyTaskCommandArgs interface.
 */
export function instanceOfApiDeleteFamilyTaskCommandArgs(value: object): boolean {
    if (!('taskId' in value)) return false;
    return true;
}

export function ApiDeleteFamilyTaskCommandArgsFromJSON(json: any): ApiDeleteFamilyTaskCommandArgs {
    return ApiDeleteFamilyTaskCommandArgsFromJSONTyped(json, false);
}

export function ApiDeleteFamilyTaskCommandArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDeleteFamilyTaskCommandArgs {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'],
    };
}

export function ApiDeleteFamilyTaskCommandArgsToJSON(value?: ApiDeleteFamilyTaskCommandArgs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'taskId': value['taskId'],
    };
}

