/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiFamilyRole = {
    Admin: 'admin',
    Member: 'member'
} as const;
export type ApiFamilyRole = typeof ApiFamilyRole[keyof typeof ApiFamilyRole];


export function ApiFamilyRoleFromJSON(json: any): ApiFamilyRole {
    return ApiFamilyRoleFromJSONTyped(json, false);
}

export function ApiFamilyRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiFamilyRole {
    return json as ApiFamilyRole;
}

export function ApiFamilyRoleToJSON(value?: ApiFamilyRole | null): any {
    return value as any;
}

