/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiFamilyTask
 */
export interface ApiFamilyTask {
    /**
     * 
     * @type {string}
     * @memberof ApiFamilyTask
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ApiFamilyTask
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiFamilyTask
     */
    memberIds: Array<string>;
}

/**
 * Check if a given object implements the ApiFamilyTask interface.
 */
export function instanceOfApiFamilyTask(value: object): boolean {
    if (!('title' in value)) return false;
    if (!('memberIds' in value)) return false;
    return true;
}

export function ApiFamilyTaskFromJSON(json: any): ApiFamilyTask {
    return ApiFamilyTaskFromJSONTyped(json, false);
}

export function ApiFamilyTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiFamilyTask {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'memberIds': json['memberIds'],
    };
}

export function ApiFamilyTaskToJSON(value?: ApiFamilyTask | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'memberIds': value['memberIds'],
    };
}

