/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiGenerateProblemsCommandArgs
 */
export interface ApiGenerateProblemsCommandArgs {
    /**
     * 
     * @type {string}
     * @memberof ApiGenerateProblemsCommandArgs
     */
    problemSetId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiGenerateProblemsCommandArgs
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiGenerateProblemsCommandArgs
     */
    additionalRequestText?: string;
}

/**
 * Check if a given object implements the ApiGenerateProblemsCommandArgs interface.
 */
export function instanceOfApiGenerateProblemsCommandArgs(value: object): boolean {
    if (!('problemSetId' in value)) return false;
    if (!('userId' in value)) return false;
    return true;
}

export function ApiGenerateProblemsCommandArgsFromJSON(json: any): ApiGenerateProblemsCommandArgs {
    return ApiGenerateProblemsCommandArgsFromJSONTyped(json, false);
}

export function ApiGenerateProblemsCommandArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiGenerateProblemsCommandArgs {
    if (json == null) {
        return json;
    }
    return {
        
        'problemSetId': json['problemSetId'],
        'userId': json['userId'],
        'additionalRequestText': json['additionalRequestText'] == null ? undefined : json['additionalRequestText'],
    };
}

export function ApiGenerateProblemsCommandArgsToJSON(value?: ApiGenerateProblemsCommandArgs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'problemSetId': value['problemSetId'],
        'userId': value['userId'],
        'additionalRequestText': value['additionalRequestText'],
    };
}

