/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiProblemForEdit } from './ApiProblemForEdit';
import {
    ApiProblemForEditFromJSON,
    ApiProblemForEditFromJSONTyped,
    ApiProblemForEditToJSON,
} from './ApiProblemForEdit';

/**
 * 
 * @export
 * @interface ApiGenerateProblemsCommandResp
 */
export interface ApiGenerateProblemsCommandResp {
    /**
     * 
     * @type {ApiProblemForEdit}
     * @memberof ApiGenerateProblemsCommandResp
     */
    problem: ApiProblemForEdit;
}

/**
 * Check if a given object implements the ApiGenerateProblemsCommandResp interface.
 */
export function instanceOfApiGenerateProblemsCommandResp(value: object): boolean {
    if (!('problem' in value)) return false;
    return true;
}

export function ApiGenerateProblemsCommandRespFromJSON(json: any): ApiGenerateProblemsCommandResp {
    return ApiGenerateProblemsCommandRespFromJSONTyped(json, false);
}

export function ApiGenerateProblemsCommandRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiGenerateProblemsCommandResp {
    if (json == null) {
        return json;
    }
    return {
        
        'problem': ApiProblemForEditFromJSON(json['problem']),
    };
}

export function ApiGenerateProblemsCommandRespToJSON(value?: ApiGenerateProblemsCommandResp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'problem': ApiProblemForEditToJSON(value['problem']),
    };
}

