/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLoadProblemForAssignmentCommandArgs
 */
export interface ApiLoadProblemForAssignmentCommandArgs {
    /**
     * 
     * @type {string}
     * @memberof ApiLoadProblemForAssignmentCommandArgs
     */
    assignmentId: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiLoadProblemForAssignmentCommandArgs
     */
    forDate: Date;
}

/**
 * Check if a given object implements the ApiLoadProblemForAssignmentCommandArgs interface.
 */
export function instanceOfApiLoadProblemForAssignmentCommandArgs(value: object): boolean {
    if (!('assignmentId' in value)) return false;
    if (!('forDate' in value)) return false;
    return true;
}

export function ApiLoadProblemForAssignmentCommandArgsFromJSON(json: any): ApiLoadProblemForAssignmentCommandArgs {
    return ApiLoadProblemForAssignmentCommandArgsFromJSONTyped(json, false);
}

export function ApiLoadProblemForAssignmentCommandArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLoadProblemForAssignmentCommandArgs {
    if (json == null) {
        return json;
    }
    return {
        
        'assignmentId': json['assignmentId'],
        'forDate': (new Date(json['forDate'])),
    };
}

export function ApiLoadProblemForAssignmentCommandArgsToJSON(value?: ApiLoadProblemForAssignmentCommandArgs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assignmentId': value['assignmentId'],
        'forDate': ((value['forDate']).toISOString()),
    };
}

