/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiProblem } from './ApiProblem';
import {
    ApiProblemFromJSON,
    ApiProblemFromJSONTyped,
    ApiProblemToJSON,
} from './ApiProblem';

/**
 * 
 * @export
 * @interface ApiLoadProblemForAssignmentCommandResult
 */
export interface ApiLoadProblemForAssignmentCommandResult {
    /**
     * 
     * @type {ApiProblem}
     * @memberof ApiLoadProblemForAssignmentCommandResult
     */
    problem: ApiProblem;
}

/**
 * Check if a given object implements the ApiLoadProblemForAssignmentCommandResult interface.
 */
export function instanceOfApiLoadProblemForAssignmentCommandResult(value: object): boolean {
    if (!('problem' in value)) return false;
    return true;
}

export function ApiLoadProblemForAssignmentCommandResultFromJSON(json: any): ApiLoadProblemForAssignmentCommandResult {
    return ApiLoadProblemForAssignmentCommandResultFromJSONTyped(json, false);
}

export function ApiLoadProblemForAssignmentCommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLoadProblemForAssignmentCommandResult {
    if (json == null) {
        return json;
    }
    return {
        
        'problem': ApiProblemFromJSON(json['problem']),
    };
}

export function ApiLoadProblemForAssignmentCommandResultToJSON(value?: ApiLoadProblemForAssignmentCommandResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'problem': ApiProblemToJSON(value['problem']),
    };
}

