/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiProblemSet
 */
export interface ApiProblemSet {
    /**
     * 
     * @type {string}
     * @memberof ApiProblemSet
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProblemSet
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProblemSet
     */
    description?: string;
}

/**
 * Check if a given object implements the ApiProblemSet interface.
 */
export function instanceOfApiProblemSet(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('title' in value)) return false;
    return true;
}

export function ApiProblemSetFromJSON(json: any): ApiProblemSet {
    return ApiProblemSetFromJSONTyped(json, false);
}

export function ApiProblemSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiProblemSet {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ApiProblemSetToJSON(value?: ApiProblemSet | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
    };
}

