/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiProblem } from './ApiProblem';
import {
    ApiProblemFromJSON,
    ApiProblemFromJSONTyped,
    ApiProblemToJSON,
} from './ApiProblem';

/**
 * Task
 * @export
 * @interface ApiProblemAssignment
 */
export interface ApiProblemAssignment {
    /**
     * 
     * @type {Array<ApiProblem>}
     * @memberof ApiProblemAssignment
     */
    problems: Array<ApiProblem>;
}

/**
 * Check if a given object implements the ApiProblemAssignment interface.
 */
export function instanceOfApiProblemAssignment(value: object): boolean {
    if (!('problems' in value)) return false;
    return true;
}

export function ApiProblemAssignmentFromJSON(json: any): ApiProblemAssignment {
    return ApiProblemAssignmentFromJSONTyped(json, false);
}

export function ApiProblemAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiProblemAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'problems': ((json['problems'] as Array<any>).map(ApiProblemFromJSON)),
    };
}

export function ApiProblemAssignmentToJSON(value?: ApiProblemAssignment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'problems': ((value['problems'] as Array<any>).map(ApiProblemToJSON)),
    };
}

