/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiProblemAnswer } from './ApiProblemAnswer';
import {
    ApiProblemAnswerFromJSON,
    ApiProblemAnswerFromJSONTyped,
    ApiProblemAnswerToJSON,
} from './ApiProblemAnswer';

/**
 * 
 * @export
 * @interface ApiProblem
 */
export interface ApiProblem {
    /**
     * 
     * @type {string}
     * @memberof ApiProblem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProblem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ApiProblem
     */
    description?: string;
    /**
     * 
     * @type {Array<ApiProblemAnswer>}
     * @memberof ApiProblem
     */
    answers: Array<ApiProblemAnswer>;
}

/**
 * Check if a given object implements the ApiProblem interface.
 */
export function instanceOfApiProblem(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('title' in value)) return false;
    if (!('answers' in value)) return false;
    return true;
}

export function ApiProblemFromJSON(json: any): ApiProblem {
    return ApiProblemFromJSONTyped(json, false);
}

export function ApiProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiProblem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'answers': ((json['answers'] as Array<any>).map(ApiProblemAnswerFromJSON)),
    };
}

export function ApiProblemToJSON(value?: ApiProblem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'answers': ((value['answers'] as Array<any>).map(ApiProblemAnswerToJSON)),
    };
}

