/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiProblemForEdit } from './ApiProblemForEdit';
import {
    ApiProblemForEditFromJSON,
    ApiProblemForEditFromJSONTyped,
    ApiProblemForEditToJSON,
} from './ApiProblemForEdit';

/**
 * 
 * @export
 * @interface ApiRefineProblemsCommandArgs
 */
export interface ApiRefineProblemsCommandArgs {
    /**
     * 
     * @type {string}
     * @memberof ApiRefineProblemsCommandArgs
     */
    problemSetId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiRefineProblemsCommandArgs
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiRefineProblemsCommandArgs
     */
    refineText: string;
    /**
     * 
     * @type {Array<ApiProblemForEdit>}
     * @memberof ApiRefineProblemsCommandArgs
     */
    problems: Array<ApiProblemForEdit>;
}

/**
 * Check if a given object implements the ApiRefineProblemsCommandArgs interface.
 */
export function instanceOfApiRefineProblemsCommandArgs(value: object): boolean {
    if (!('problemSetId' in value)) return false;
    if (!('userId' in value)) return false;
    if (!('refineText' in value)) return false;
    if (!('problems' in value)) return false;
    return true;
}

export function ApiRefineProblemsCommandArgsFromJSON(json: any): ApiRefineProblemsCommandArgs {
    return ApiRefineProblemsCommandArgsFromJSONTyped(json, false);
}

export function ApiRefineProblemsCommandArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRefineProblemsCommandArgs {
    if (json == null) {
        return json;
    }
    return {
        
        'problemSetId': json['problemSetId'],
        'userId': json['userId'],
        'refineText': json['refineText'],
        'problems': ((json['problems'] as Array<any>).map(ApiProblemForEditFromJSON)),
    };
}

export function ApiRefineProblemsCommandArgsToJSON(value?: ApiRefineProblemsCommandArgs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'problemSetId': value['problemSetId'],
        'userId': value['userId'],
        'refineText': value['refineText'],
        'problems': ((value['problems'] as Array<any>).map(ApiProblemForEditToJSON)),
    };
}

