/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSubmitProblemAnswerCommandArgs
 */
export interface ApiSubmitProblemAnswerCommandArgs {
    /**
     * 
     * @type {string}
     * @memberof ApiSubmitProblemAnswerCommandArgs
     */
    assignmentId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiSubmitProblemAnswerCommandArgs
     */
    problemId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiSubmitProblemAnswerCommandArgs
     */
    answerId: string;
}

/**
 * Check if a given object implements the ApiSubmitProblemAnswerCommandArgs interface.
 */
export function instanceOfApiSubmitProblemAnswerCommandArgs(value: object): boolean {
    if (!('assignmentId' in value)) return false;
    if (!('problemId' in value)) return false;
    if (!('answerId' in value)) return false;
    return true;
}

export function ApiSubmitProblemAnswerCommandArgsFromJSON(json: any): ApiSubmitProblemAnswerCommandArgs {
    return ApiSubmitProblemAnswerCommandArgsFromJSONTyped(json, false);
}

export function ApiSubmitProblemAnswerCommandArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSubmitProblemAnswerCommandArgs {
    if (json == null) {
        return json;
    }
    return {
        
        'assignmentId': json['assignmentId'],
        'problemId': json['problemId'],
        'answerId': json['answerId'],
    };
}

export function ApiSubmitProblemAnswerCommandArgsToJSON(value?: ApiSubmitProblemAnswerCommandArgs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assignmentId': value['assignmentId'],
        'problemId': value['problemId'],
        'answerId': value['answerId'],
    };
}

