/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSubmitProblemAnswerCommandResp
 */
export interface ApiSubmitProblemAnswerCommandResp {
    /**
     * 
     * @type {boolean}
     * @memberof ApiSubmitProblemAnswerCommandResp
     */
    isCorrect: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiSubmitProblemAnswerCommandResp
     */
    correctAnswerId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiSubmitProblemAnswerCommandResp
     */
    explanation?: string;
}

/**
 * Check if a given object implements the ApiSubmitProblemAnswerCommandResp interface.
 */
export function instanceOfApiSubmitProblemAnswerCommandResp(value: object): boolean {
    if (!('isCorrect' in value)) return false;
    if (!('correctAnswerId' in value)) return false;
    return true;
}

export function ApiSubmitProblemAnswerCommandRespFromJSON(json: any): ApiSubmitProblemAnswerCommandResp {
    return ApiSubmitProblemAnswerCommandRespFromJSONTyped(json, false);
}

export function ApiSubmitProblemAnswerCommandRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSubmitProblemAnswerCommandResp {
    if (json == null) {
        return json;
    }
    return {
        
        'isCorrect': json['isCorrect'],
        'correctAnswerId': json['correctAnswerId'],
        'explanation': json['explanation'] == null ? undefined : json['explanation'],
    };
}

export function ApiSubmitProblemAnswerCommandRespToJSON(value?: ApiSubmitProblemAnswerCommandResp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isCorrect': value['isCorrect'],
        'correctAnswerId': value['correctAnswerId'],
        'explanation': value['explanation'],
    };
}

