/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiTaskStatus = {
    Open: 'open',
    Done: 'done',
    Blocked: 'blocked',
    Irrelevant: 'irrelevant'
} as const;
export type ApiTaskStatus = typeof ApiTaskStatus[keyof typeof ApiTaskStatus];


export function ApiTaskStatusFromJSON(json: any): ApiTaskStatus {
    return ApiTaskStatusFromJSONTyped(json, false);
}

export function ApiTaskStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTaskStatus {
    return json as ApiTaskStatus;
}

export function ApiTaskStatusToJSON(value?: ApiTaskStatus | null): any {
    return value as any;
}

