/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiFamilyTask } from './ApiFamilyTask';
import {
    ApiFamilyTaskFromJSON,
    ApiFamilyTaskFromJSONTyped,
    ApiFamilyTaskToJSON,
} from './ApiFamilyTask';

/**
 * 
 * @export
 * @interface ApiUpdateFamilyTaskCommandArgs
 */
export interface ApiUpdateFamilyTaskCommandArgs {
    /**
     * 
     * @type {ApiFamilyTask}
     * @memberof ApiUpdateFamilyTaskCommandArgs
     */
    task: ApiFamilyTask;
}

/**
 * Check if a given object implements the ApiUpdateFamilyTaskCommandArgs interface.
 */
export function instanceOfApiUpdateFamilyTaskCommandArgs(value: object): boolean {
    if (!('task' in value)) return false;
    return true;
}

export function ApiUpdateFamilyTaskCommandArgsFromJSON(json: any): ApiUpdateFamilyTaskCommandArgs {
    return ApiUpdateFamilyTaskCommandArgsFromJSONTyped(json, false);
}

export function ApiUpdateFamilyTaskCommandArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUpdateFamilyTaskCommandArgs {
    if (json == null) {
        return json;
    }
    return {
        
        'task': ApiFamilyTaskFromJSON(json['task']),
    };
}

export function ApiUpdateFamilyTaskCommandArgsToJSON(value?: ApiUpdateFamilyTaskCommandArgs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'task': ApiFamilyTaskToJSON(value['task']),
    };
}

