/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTaskStatus } from './ApiTaskStatus';
import {
    ApiTaskStatusFromJSON,
    ApiTaskStatusFromJSONTyped,
    ApiTaskStatusToJSON,
} from './ApiTaskStatus';

/**
 * 
 * @export
 * @interface ApiUpdateTaskStatusCommandArgs
 */
export interface ApiUpdateTaskStatusCommandArgs {
    /**
     * 
     * @type {string}
     * @memberof ApiUpdateTaskStatusCommandArgs
     */
    taskId: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiUpdateTaskStatusCommandArgs
     */
    forDate: Date;
    /**
     * 
     * @type {ApiTaskStatus}
     * @memberof ApiUpdateTaskStatusCommandArgs
     */
    status: ApiTaskStatus;
    /**
     * 
     * @type {string}
     * @memberof ApiUpdateTaskStatusCommandArgs
     */
    comment?: string;
}

/**
 * Check if a given object implements the ApiUpdateTaskStatusCommandArgs interface.
 */
export function instanceOfApiUpdateTaskStatusCommandArgs(value: object): boolean {
    if (!('taskId' in value)) return false;
    if (!('forDate' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function ApiUpdateTaskStatusCommandArgsFromJSON(json: any): ApiUpdateTaskStatusCommandArgs {
    return ApiUpdateTaskStatusCommandArgsFromJSONTyped(json, false);
}

export function ApiUpdateTaskStatusCommandArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUpdateTaskStatusCommandArgs {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'],
        'forDate': (new Date(json['forDate'])),
        'status': ApiTaskStatusFromJSON(json['status']),
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function ApiUpdateTaskStatusCommandArgsToJSON(value?: ApiUpdateTaskStatusCommandArgs | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'taskId': value['taskId'],
        'forDate': ((value['forDate']).toISOString()),
        'status': ApiTaskStatusToJSON(value['status']),
        'comment': value['comment'],
    };
}

