/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UIFamilyTask
 */
export interface UIFamilyTask {
    /**
     * 
     * @type {string}
     * @memberof UIFamilyTask
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UIFamilyTask
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof UIFamilyTask
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UIFamilyTask
     */
    memberIds: Array<string>;
}

/**
 * Check if a given object implements the UIFamilyTask interface.
 */
export function instanceOfUIFamilyTask(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('title' in value)) return false;
    if (!('memberIds' in value)) return false;
    return true;
}

export function UIFamilyTaskFromJSON(json: any): UIFamilyTask {
    return UIFamilyTaskFromJSONTyped(json, false);
}

export function UIFamilyTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): UIFamilyTask {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'memberIds': json['memberIds'],
    };
}

export function UIFamilyTaskToJSON(value?: UIFamilyTask | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'memberIds': value['memberIds'],
    };
}

