/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User Info
 * @export
 * @interface UIUserInfo
 */
export interface UIUserInfo {
    /**
     * 
     * @type {string}
     * @memberof UIUserInfo
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UIUserInfo
     */
    familyDisplayName: string;
    /**
     * 
     * @type {string}
     * @memberof UIUserInfo
     */
    familyUri: string;
    /**
     * 
     * @type {string}
     * @memberof UIUserInfo
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UIUserInfo
     */
    lastName?: string;
}

/**
 * Check if a given object implements the UIUserInfo interface.
 */
export function instanceOfUIUserInfo(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('familyDisplayName' in value)) return false;
    if (!('familyUri' in value)) return false;
    return true;
}

export function UIUserInfoFromJSON(json: any): UIUserInfo {
    return UIUserInfoFromJSONTyped(json, false);
}

export function UIUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UIUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'familyDisplayName': json['familyDisplayName'],
        'familyUri': json['familyUri'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
    };
}

export function UIUserInfoToJSON(value?: UIUserInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'familyDisplayName': value['familyDisplayName'],
        'familyUri': value['familyUri'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

