/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UIUserRole = {
    FamilyAdmin: 'familyAdmin',
    FamilyMember: 'familyMember',
    Guest: 'guest'
} as const;
export type UIUserRole = typeof UIUserRole[keyof typeof UIUserRole];


export function UIUserRoleFromJSON(json: any): UIUserRole {
    return UIUserRoleFromJSONTyped(json, false);
}

export function UIUserRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UIUserRole {
    return json as UIUserRole;
}

export function UIUserRoleToJSON(value?: UIUserRole | null): any {
    return value as any;
}

