/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiCreateFamilyTaskCommandArgs,
  ApiDeleteFamilyTaskCommandArgs,
  ApiTask,
  ApiUpdateFamilyTaskCommandArgs,
  ApiUpdateTaskStatusCommandArgs,
} from '../models/index';
import {
    ApiCreateFamilyTaskCommandArgsFromJSON,
    ApiCreateFamilyTaskCommandArgsToJSON,
    ApiDeleteFamilyTaskCommandArgsFromJSON,
    ApiDeleteFamilyTaskCommandArgsToJSON,
    ApiTaskFromJSON,
    ApiTaskToJSON,
    ApiUpdateFamilyTaskCommandArgsFromJSON,
    ApiUpdateFamilyTaskCommandArgsToJSON,
    ApiUpdateTaskStatusCommandArgsFromJSON,
    ApiUpdateTaskStatusCommandArgsToJSON,
} from '../models/index';

export interface CreateFamilyTaskRequest {
    apiCreateFamilyTaskCommandArgs?: ApiCreateFamilyTaskCommandArgs;
}

export interface DeleteFamilyTaskRequest {
    apiDeleteFamilyTaskCommandArgs?: ApiDeleteFamilyTaskCommandArgs;
}

export interface UpdateFamilyTaskRequest {
    apiUpdateFamilyTaskCommandArgs?: ApiUpdateFamilyTaskCommandArgs;
}

export interface UpdateTaskStatusRequest {
    apiUpdateTaskStatusCommandArgs?: ApiUpdateTaskStatusCommandArgs;
}

/**
 * 
 */
export class ShpankidsApi extends runtime.BaseAPI {

    /**
     * Create Family Task
     */
    async createFamilyTaskRaw(requestParameters: CreateFamilyTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/commands/create-family-task`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiCreateFamilyTaskCommandArgsToJSON(requestParameters['apiCreateFamilyTaskCommandArgs']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create Family Task
     */
    async createFamilyTask(requestParameters: CreateFamilyTaskRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createFamilyTaskRaw(requestParameters, initOverrides);
    }

    /**
     * Delete Family Task
     */
    async deleteFamilyTaskRaw(requestParameters: DeleteFamilyTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/commands/delete-family-task`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiDeleteFamilyTaskCommandArgsToJSON(requestParameters['apiDeleteFamilyTaskCommandArgs']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Family Task
     */
    async deleteFamilyTask(requestParameters: DeleteFamilyTaskRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFamilyTaskRaw(requestParameters, initOverrides);
    }

    /**
     * list Tasks
     */
    async listTasksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiTask>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/tasks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiTaskFromJSON));
    }

    /**
     * list Tasks
     */
    async listTasks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiTask>> {
        const response = await this.listTasksRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Family Task
     */
    async updateFamilyTaskRaw(requestParameters: UpdateFamilyTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/commands/update-family-task`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiUpdateFamilyTaskCommandArgsToJSON(requestParameters['apiUpdateFamilyTaskCommandArgs']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Family Task
     */
    async updateFamilyTask(requestParameters: UpdateFamilyTaskRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateFamilyTaskRaw(requestParameters, initOverrides);
    }

    /**
     * Update Task Status
     */
    async updateTaskStatusRaw(requestParameters: UpdateTaskStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/commands/update-task-status`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiUpdateTaskStatusCommandArgsToJSON(requestParameters['apiUpdateTaskStatusCommandArgs']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Task Status
     */
    async updateTaskStatus(requestParameters: UpdateTaskStatusRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateTaskStatusRaw(requestParameters, initOverrides);
    }

}
