/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiTask,
  ApiUpdateTaskStatusCommandArgs,
} from '../models/index';
import {
    ApiTaskFromJSON,
    ApiTaskToJSON,
    ApiUpdateTaskStatusCommandArgsFromJSON,
    ApiUpdateTaskStatusCommandArgsToJSON,
} from '../models/index';

export interface UpdateTaskStatusRequest {
    apiUpdateTaskStatusCommandArgs?: ApiUpdateTaskStatusCommandArgs;
}

/**
 * 
 */
export class ShpankidsApi extends runtime.BaseAPI {

    /**
     * list Tasks
     */
    async listTasksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiTask>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/tasks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiTaskFromJSON));
    }

    /**
     * list Tasks
     */
    async listTasks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiTask>> {
        const response = await this.listTasksRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Task Status
     */
    async updateTaskStatusRaw(requestParameters: UpdateTaskStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/commands/updateTaskStatus`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiUpdateTaskStatusCommandArgsToJSON(requestParameters['apiUpdateTaskStatusCommandArgs']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Task Status
     */
    async updateTaskStatus(requestParameters: UpdateTaskStatusRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateTaskStatusRaw(requestParameters, initOverrides);
    }

}
