/* tslint:disable */
/* eslint-disable */
/**
 * ShpanKids API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UIFamilyInfo,
  UIUserInfo,
} from '../models/index';
import {
    UIFamilyInfoFromJSON,
    UIFamilyInfoToJSON,
    UIUserInfoFromJSON,
    UIUserInfoToJSON,
} from '../models/index';

/**
 * 
 */
export class UIApi extends runtime.BaseAPI {

    /**
     * Get session family info
     */
    async getFamilyInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UIFamilyInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/ui/familyInfo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UIFamilyInfoFromJSON(jsonValue));
    }

    /**
     * Get session family info
     */
    async getFamilyInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UIFamilyInfo> {
        const response = await this.getFamilyInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get logged in user info
     */
    async getUserInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UIUserInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/ui/userInfo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UIUserInfoFromJSON(jsonValue));
    }

    /**
     * Get logged in user info
     */
    async getUserInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UIUserInfo> {
        const response = await this.getUserInfoRaw(initOverrides);
        return await response.value();
    }

}
