// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApiAssignmentStatus.
const (
	Blocked    ApiAssignmentStatus = "blocked"
	Done       ApiAssignmentStatus = "done"
	Irrelevant ApiAssignmentStatus = "irrelevant"
	Open       ApiAssignmentStatus = "open"
)

// Defines values for ApiAssignmentType.
const (
	ProblemSet ApiAssignmentType = "problemSet"
	Task       ApiAssignmentType = "task"
)

// Defines values for ApiFamilyRole.
const (
	Admin  ApiFamilyRole = "admin"
	Member ApiFamilyRole = "member"
)

// ApiAssignment defines model for ApiAssignment.
type ApiAssignment struct {
	Description *string             `json:"description,omitempty"`
	ForDate     time.Time           `json:"forDate"`
	Id          string              `json:"id"`
	Status      ApiAssignmentStatus `json:"status"`
	Title       string              `json:"title"`
	Type        ApiAssignmentType   `json:"type"`
}

// ApiAssignmentStatus defines model for ApiAssignmentStatus.
type ApiAssignmentStatus string

// ApiAssignmentType defines model for ApiAssignmentType.
type ApiAssignmentType string

// ApiCreateFamilyTaskCommandArgs defines model for ApiCreateFamilyTaskCommandArgs.
type ApiCreateFamilyTaskCommandArgs struct {
	Task ApiFamilyTask `json:"task"`
}

// ApiDeleteFamilyTaskCommandArgs defines model for ApiDeleteFamilyTaskCommandArgs.
type ApiDeleteFamilyTaskCommandArgs struct {
	TaskId string `json:"taskId"`
}

// ApiFamilyRole defines model for ApiFamilyRole.
type ApiFamilyRole string

// ApiFamilyTask defines model for ApiFamilyTask.
type ApiFamilyTask struct {
	Description *string  `json:"description,omitempty"`
	MemberIds   []string `json:"memberIds"`
	Title       string   `json:"title"`
}

// ApiLoadProblemForAssignmentCommandArgs defines model for ApiLoadProblemForAssignmentCommandArgs.
type ApiLoadProblemForAssignmentCommandArgs struct {
	AssignmentId string    `json:"assignmentId"`
	ForDate      time.Time `json:"forDate"`
}

// ApiLoadProblemForAssignmentCommandResult defines model for ApiLoadProblemForAssignmentCommandResult.
type ApiLoadProblemForAssignmentCommandResult struct {
	Problem ApiProblem `json:"problem"`
}

// ApiProblem defines model for ApiProblem.
type ApiProblem struct {
	Answers     []ApiProblemAnswer `json:"answers"`
	Description *string            `json:"description,omitempty"`
	Id          string             `json:"id"`
	Title       string             `json:"title"`
}

// ApiProblemAnswer defines model for ApiProblemAnswer.
type ApiProblemAnswer struct {
	Id    string `json:"id"`
	Title string `json:"title"`
}

// ApiTaskStats defines model for ApiTaskStats.
type ApiTaskStats struct {
	DoneTasksCount  int       `json:"doneTasksCount"`
	ForDate         time.Time `json:"forDate"`
	TotalTasksCount int       `json:"totalTasksCount"`
	UserId          string    `json:"userId"`
}

// ApiUpdateFamilyTaskCommandArgs defines model for ApiUpdateFamilyTaskCommandArgs.
type ApiUpdateFamilyTaskCommandArgs struct {
	Task ApiFamilyTask `json:"task"`
}

// ApiUpdateTaskStatusCommandArgs defines model for ApiUpdateTaskStatusCommandArgs.
type ApiUpdateTaskStatusCommandArgs struct {
	Comment *string             `json:"comment,omitempty"`
	ForDate time.Time           `json:"forDate"`
	Status  ApiAssignmentStatus `json:"status"`
	TaskId  string              `json:"taskId"`
}

// UIFamilyInfo Family info
type UIFamilyInfo struct {
	AdminEmail        openapi_types.Email `json:"adminEmail"`
	FamilyDisplayName string              `json:"familyDisplayName"`
	FamilyUri         string              `json:"familyUri"`
	Members           []UIFamilyMember    `json:"members"`
	Tasks             []UIFamilyTask      `json:"tasks"`
}

// UIFamilyMember Family member
type UIFamilyMember struct {
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"firstName"`
	LastName  string              `json:"lastName"`
	Role      ApiFamilyRole       `json:"role"`
}

// UIFamilyTask defines model for UIFamilyTask.
type UIFamilyTask struct {
	Description *string  `json:"description,omitempty"`
	Id          string   `json:"id"`
	MemberIds   []string `json:"memberIds"`
	Title       string   `json:"title"`
}

// UIUserInfo User Info
type UIUserInfo struct {
	Email             openapi_types.Email `json:"email"`
	FamilyDisplayName string              `json:"familyDisplayName"`
	FamilyUri         string              `json:"familyUri"`
	FirstName         *string             `json:"firstName,omitempty"`
	LastName          *string             `json:"lastName,omitempty"`
}

// GetStatsParams defines parameters for GetStats.
type GetStatsParams struct {
	// From From date
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To To date
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// CreateFamilyTaskJSONRequestBody defines body for CreateFamilyTask for application/json ContentType.
type CreateFamilyTaskJSONRequestBody = ApiCreateFamilyTaskCommandArgs

// DeleteFamilyTaskJSONRequestBody defines body for DeleteFamilyTask for application/json ContentType.
type DeleteFamilyTaskJSONRequestBody = ApiDeleteFamilyTaskCommandArgs

// LoadProblemForAssignmentJSONRequestBody defines body for LoadProblemForAssignment for application/json ContentType.
type LoadProblemForAssignmentJSONRequestBody = ApiLoadProblemForAssignmentCommandArgs

// UpdateFamilyTaskJSONRequestBody defines body for UpdateFamilyTask for application/json ContentType.
type UpdateFamilyTaskJSONRequestBody = ApiUpdateFamilyTaskCommandArgs

// UpdateTaskStatusJSONRequestBody defines body for UpdateTaskStatus for application/json ContentType.
type UpdateTaskStatusJSONRequestBody = ApiUpdateTaskStatusCommandArgs

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/assignments)
	ListAssignments(w http.ResponseWriter, r *http.Request)

	// (POST /api/commands/create-family-task)
	CreateFamilyTask(w http.ResponseWriter, r *http.Request)

	// (POST /api/commands/delete-family-task)
	DeleteFamilyTask(w http.ResponseWriter, r *http.Request)

	// (POST /api/commands/load-problem-for-assignment)
	LoadProblemForAssignment(w http.ResponseWriter, r *http.Request)

	// (POST /api/commands/update-family-task)
	UpdateFamilyTask(w http.ResponseWriter, r *http.Request)

	// (POST /api/commands/update-task-status)
	UpdateTaskStatus(w http.ResponseWriter, r *http.Request)

	// (GET /api/stats)
	GetStats(w http.ResponseWriter, r *http.Request, params GetStatsParams)

	// (GET /api/ui/familyInfo)
	GetFamilyInfo(w http.ResponseWriter, r *http.Request)

	// (GET /api/ui/userInfo)
	GetUserInfo(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAssignments operation middleware
func (siw *ServerInterfaceWrapper) ListAssignments(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAssignments(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateFamilyTask operation middleware
func (siw *ServerInterfaceWrapper) CreateFamilyTask(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFamilyTask(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteFamilyTask operation middleware
func (siw *ServerInterfaceWrapper) DeleteFamilyTask(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFamilyTask(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// LoadProblemForAssignment operation middleware
func (siw *ServerInterfaceWrapper) LoadProblemForAssignment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadProblemForAssignment(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateFamilyTask operation middleware
func (siw *ServerInterfaceWrapper) UpdateFamilyTask(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateFamilyTask(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateTaskStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateTaskStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTaskStatus(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStatsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetFamilyInfo operation middleware
func (siw *ServerInterfaceWrapper) GetFamilyInfo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFamilyInfo(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetUserInfo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserInfo(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/api/assignments", wrapper.ListAssignments).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/commands/create-family-task", wrapper.CreateFamilyTask).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/commands/delete-family-task", wrapper.DeleteFamilyTask).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/commands/load-problem-for-assignment", wrapper.LoadProblemForAssignment).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/commands/update-family-task", wrapper.UpdateFamilyTask).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/commands/update-task-status", wrapper.UpdateTaskStatus).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/stats", wrapper.GetStats).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/ui/familyInfo", wrapper.GetFamilyInfo).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/ui/userInfo", wrapper.GetUserInfo).Methods("GET")

	return r
}

type ListAssignmentsRequestObject struct {
}

type ListAssignmentsResponseObject interface {
	VisitListAssignmentsResponse(w http.ResponseWriter) error
}

type ListAssignments200JSONResponse []ApiAssignment

func (response ListAssignments200JSONResponse) VisitListAssignmentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateFamilyTaskRequestObject struct {
	Body *CreateFamilyTaskJSONRequestBody
}

type CreateFamilyTaskResponseObject interface {
	VisitCreateFamilyTaskResponse(w http.ResponseWriter) error
}

type CreateFamilyTask200Response struct {
}

func (response CreateFamilyTask200Response) VisitCreateFamilyTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteFamilyTaskRequestObject struct {
	Body *DeleteFamilyTaskJSONRequestBody
}

type DeleteFamilyTaskResponseObject interface {
	VisitDeleteFamilyTaskResponse(w http.ResponseWriter) error
}

type DeleteFamilyTask200Response struct {
}

func (response DeleteFamilyTask200Response) VisitDeleteFamilyTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type LoadProblemForAssignmentRequestObject struct {
	Body *LoadProblemForAssignmentJSONRequestBody
}

type LoadProblemForAssignmentResponseObject interface {
	VisitLoadProblemForAssignmentResponse(w http.ResponseWriter) error
}

type LoadProblemForAssignment200JSONResponse ApiLoadProblemForAssignmentCommandResult

func (response LoadProblemForAssignment200JSONResponse) VisitLoadProblemForAssignmentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFamilyTaskRequestObject struct {
	Body *UpdateFamilyTaskJSONRequestBody
}

type UpdateFamilyTaskResponseObject interface {
	VisitUpdateFamilyTaskResponse(w http.ResponseWriter) error
}

type UpdateFamilyTask200Response struct {
}

func (response UpdateFamilyTask200Response) VisitUpdateFamilyTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateTaskStatusRequestObject struct {
	Body *UpdateTaskStatusJSONRequestBody
}

type UpdateTaskStatusResponseObject interface {
	VisitUpdateTaskStatusResponse(w http.ResponseWriter) error
}

type UpdateTaskStatus200Response struct {
}

func (response UpdateTaskStatus200Response) VisitUpdateTaskStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetStatsRequestObject struct {
	Params GetStatsParams
}

type GetStatsResponseObject interface {
	VisitGetStatsResponse(w http.ResponseWriter) error
}

type GetStats200JSONResponse []ApiTaskStats

func (response GetStats200JSONResponse) VisitGetStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFamilyInfoRequestObject struct {
}

type GetFamilyInfoResponseObject interface {
	VisitGetFamilyInfoResponse(w http.ResponseWriter) error
}

type GetFamilyInfo200JSONResponse UIFamilyInfo

func (response GetFamilyInfo200JSONResponse) VisitGetFamilyInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserInfoRequestObject struct {
}

type GetUserInfoResponseObject interface {
	VisitGetUserInfoResponse(w http.ResponseWriter) error
}

type GetUserInfo200JSONResponse UIUserInfo

func (response GetUserInfo200JSONResponse) VisitGetUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/assignments)
	ListAssignments(ctx context.Context, request ListAssignmentsRequestObject) (ListAssignmentsResponseObject, error)

	// (POST /api/commands/create-family-task)
	CreateFamilyTask(ctx context.Context, request CreateFamilyTaskRequestObject) (CreateFamilyTaskResponseObject, error)

	// (POST /api/commands/delete-family-task)
	DeleteFamilyTask(ctx context.Context, request DeleteFamilyTaskRequestObject) (DeleteFamilyTaskResponseObject, error)

	// (POST /api/commands/load-problem-for-assignment)
	LoadProblemForAssignment(ctx context.Context, request LoadProblemForAssignmentRequestObject) (LoadProblemForAssignmentResponseObject, error)

	// (POST /api/commands/update-family-task)
	UpdateFamilyTask(ctx context.Context, request UpdateFamilyTaskRequestObject) (UpdateFamilyTaskResponseObject, error)

	// (POST /api/commands/update-task-status)
	UpdateTaskStatus(ctx context.Context, request UpdateTaskStatusRequestObject) (UpdateTaskStatusResponseObject, error)

	// (GET /api/stats)
	GetStats(ctx context.Context, request GetStatsRequestObject) (GetStatsResponseObject, error)

	// (GET /api/ui/familyInfo)
	GetFamilyInfo(ctx context.Context, request GetFamilyInfoRequestObject) (GetFamilyInfoResponseObject, error)

	// (GET /api/ui/userInfo)
	GetUserInfo(ctx context.Context, request GetUserInfoRequestObject) (GetUserInfoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAssignments operation middleware
func (sh *strictHandler) ListAssignments(w http.ResponseWriter, r *http.Request) {
	var request ListAssignmentsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAssignments(ctx, request.(ListAssignmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAssignments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAssignmentsResponseObject); ok {
		if err := validResponse.VisitListAssignmentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateFamilyTask operation middleware
func (sh *strictHandler) CreateFamilyTask(w http.ResponseWriter, r *http.Request) {
	var request CreateFamilyTaskRequestObject

	var body CreateFamilyTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateFamilyTask(ctx, request.(CreateFamilyTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateFamilyTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateFamilyTaskResponseObject); ok {
		if err := validResponse.VisitCreateFamilyTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFamilyTask operation middleware
func (sh *strictHandler) DeleteFamilyTask(w http.ResponseWriter, r *http.Request) {
	var request DeleteFamilyTaskRequestObject

	var body DeleteFamilyTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFamilyTask(ctx, request.(DeleteFamilyTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFamilyTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFamilyTaskResponseObject); ok {
		if err := validResponse.VisitDeleteFamilyTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoadProblemForAssignment operation middleware
func (sh *strictHandler) LoadProblemForAssignment(w http.ResponseWriter, r *http.Request) {
	var request LoadProblemForAssignmentRequestObject

	var body LoadProblemForAssignmentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoadProblemForAssignment(ctx, request.(LoadProblemForAssignmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoadProblemForAssignment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoadProblemForAssignmentResponseObject); ok {
		if err := validResponse.VisitLoadProblemForAssignmentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateFamilyTask operation middleware
func (sh *strictHandler) UpdateFamilyTask(w http.ResponseWriter, r *http.Request) {
	var request UpdateFamilyTaskRequestObject

	var body UpdateFamilyTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateFamilyTask(ctx, request.(UpdateFamilyTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateFamilyTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateFamilyTaskResponseObject); ok {
		if err := validResponse.VisitUpdateFamilyTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTaskStatus operation middleware
func (sh *strictHandler) UpdateTaskStatus(w http.ResponseWriter, r *http.Request) {
	var request UpdateTaskStatusRequestObject

	var body UpdateTaskStatusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTaskStatus(ctx, request.(UpdateTaskStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTaskStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTaskStatusResponseObject); ok {
		if err := validResponse.VisitUpdateTaskStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStats operation middleware
func (sh *strictHandler) GetStats(w http.ResponseWriter, r *http.Request, params GetStatsParams) {
	var request GetStatsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStats(ctx, request.(GetStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatsResponseObject); ok {
		if err := validResponse.VisitGetStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFamilyInfo operation middleware
func (sh *strictHandler) GetFamilyInfo(w http.ResponseWriter, r *http.Request) {
	var request GetFamilyInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFamilyInfo(ctx, request.(GetFamilyInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFamilyInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFamilyInfoResponseObject); ok {
		if err := validResponse.VisitGetFamilyInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserInfo operation middleware
func (sh *strictHandler) GetUserInfo(w http.ResponseWriter, r *http.Request) {
	var request GetUserInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserInfo(ctx, request.(GetUserInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserInfoResponseObject); ok {
		if err := validResponse.VisitGetUserInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYy3LbNhd+FQ7+f0lFbrvTTrWbjCZp64mtlccLmDyUERMAA4BpNR69e+cAoHgDKdK2",
	"PNnZAHEu37l+eiaJ5IUUIIwmq2eik0fg1P65Lthaa7YTHITBg0LJApRhYK9T0IlihWFS4L9mXwBZEW0U",
	"EztyiEkm1RU1gHeZVJwasiIpNbAwjAOJ+w9YGpSjDTWl1fh/BRlZkf8ta5OX3t5ly9gb9+QQE8NMDkGx",
	"7mCG0Ft8cDjERMH3kilIyeoObfaiKl2140fT74/OyodvkBhUH7J39UxAlBzlygIEiUkqBcp5yGXyBKiK",
	"KQU5/KDCNKTWTvUNbsg0VD+RGKP4kAO/gUERlwqogY+Us3x/S/XTpeScinStdrqfBlbqaRxraT0MrYQB",
	"jK4gh1mmbEJJFFC4SYdUOmVfZd4Cj6acYUQ48AdQQ8g1vJxdL07yJrUfMwNcj+QtoUrR/ViGBxPVZ2it",
	"agCDL5Km1y5PPkpVp9Qo/PT42SZ9i47Q8aAlvhb2Mg++gi7zQFPzxTEhob3wnpmVhAG7rmsFHfSE/gdU",
	"O/jTTFjbl6HcOJVyAx33JSlVmT/utje15/ybGTKgHisSm2wga7HF4rW+lKUbc14AEwZ2DtfZo8xIQ/NT",
	"UkuNNXjavXqe+Bdx1+i+wgEctkX6s3R2Z0oVmFKPmpJIXi0hr98zXrdQzJsxE7eB7cahuBGZ7M0K4u4i",
	"hpdxt23gXPqDU5a3AAB7EnA+s7KumC5yuv+L8vBy5L7aKjYyqaa3qsq7P93sDA0xzNzZ8lzOdaV1q+fo",
	"StwEK4RE7Vll0VisvDdD0fKLQjdeMCNUTGkzGKKcjlwqv71MKl276nRhq6yqjWio9ArG0HnZDjQwB36a",
	"1Wi72WILDlYp3kSbUI3C+5bni/NmKAUChVJb0IcJ5TAPkQ8BuXksqPjMUh2trzckJj9AaQfbxYdf0Cwk",
	"PLRgZEV++4BHMSmoebTwLWnBlvX2Z892YPoRyJk20brxoRWrKF5jzyZfmDbtewW6kEK7OP16ceGGjTB+",
	"2NCiyFliBSy/aZe0rn7m7GkNFt3vVt01jfz92UbCUByEd0Qjck8MExKPLRiJm5V6mVimtnDRWFQDu5A6",
	"gI5jdZFvT7eODLbx6RI/4hICtPldpvtZ2JyAZIxiHg4uE/uReTlQqeWR04BynHMUqC4tPR9QYwT4HEDl",
	"kqYLz2EWmVQL2v4JKIgYki0dCfjXRP5plEkVNZ72KnGAnp0PyCmUdhjQd7LC09JXdoXSrtbTkt2t4aPJ",
	"3iUN54vRGD05R7J7oBChRc0KRoFCsyJPB8JA1ZTm3ECFydMbAqUryhwctxYK/IRpw5I+HJ/AOM6Ns1xR",
	"DsaShrvewqwkj1LHkRgefC9B7UlMhF1TSKYkR/p0BGfaj0c9c+WYEiPnq7h/p/2h/vXibdaHki2zFt0M",
	"hvcTmEiDxjUtyloMtBfmBnk9Y/tskeTTnm83bZfLxuY+6HAudztIIyYi/HzQ4SMLOKu7Ry1Tna0Pnqu8",
	"bi/eh/vDfwEAAP//8BPpA/EZAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
