// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApiFamilyRole.
const (
	Admin  ApiFamilyRole = "admin"
	Member ApiFamilyRole = "member"
)

// Defines values for ApiTaskStatus.
const (
	Blocked    ApiTaskStatus = "blocked"
	Done       ApiTaskStatus = "done"
	Irrelevant ApiTaskStatus = "irrelevant"
	Open       ApiTaskStatus = "open"
)

// ApiCreateFamilyTaskCommandArgs defines model for ApiCreateFamilyTaskCommandArgs.
type ApiCreateFamilyTaskCommandArgs struct {
	Task ApiFamilyTask `json:"task"`
}

// ApiDeleteFamilyTaskCommandArgs defines model for ApiDeleteFamilyTaskCommandArgs.
type ApiDeleteFamilyTaskCommandArgs struct {
	TaskId string `json:"taskId"`
}

// ApiFamilyRole defines model for ApiFamilyRole.
type ApiFamilyRole string

// ApiFamilyTask defines model for ApiFamilyTask.
type ApiFamilyTask struct {
	Description *string  `json:"description,omitempty"`
	MemberIds   []string `json:"memberIds"`
	Title       string   `json:"title"`
}

// ApiTask Task
type ApiTask struct {
	Description string        `json:"description"`
	DueDate     *time.Time    `json:"dueDate,omitempty"`
	ForDate     time.Time     `json:"forDate"`
	Id          string        `json:"id"`
	Status      ApiTaskStatus `json:"status"`
	Title       string        `json:"title"`
}

// ApiTaskStats defines model for ApiTaskStats.
type ApiTaskStats struct {
	DoneTasksCount  int       `json:"doneTasksCount"`
	ForDate         time.Time `json:"forDate"`
	TotalTasksCount int       `json:"totalTasksCount"`
	UserId          string    `json:"userId"`
}

// ApiTaskStatus defines model for ApiTaskStatus.
type ApiTaskStatus string

// ApiUpdateFamilyTaskCommandArgs defines model for ApiUpdateFamilyTaskCommandArgs.
type ApiUpdateFamilyTaskCommandArgs struct {
	Task ApiFamilyTask `json:"task"`
}

// ApiUpdateTaskStatusCommandArgs defines model for ApiUpdateTaskStatusCommandArgs.
type ApiUpdateTaskStatusCommandArgs struct {
	Comment *string       `json:"comment,omitempty"`
	ForDate time.Time     `json:"forDate"`
	Status  ApiTaskStatus `json:"status"`
	TaskId  string        `json:"taskId"`
}

// UIFamilyInfo Family info
type UIFamilyInfo struct {
	AdminEmail        openapi_types.Email `json:"adminEmail"`
	FamilyDisplayName string              `json:"familyDisplayName"`
	FamilyUri         string              `json:"familyUri"`
	Members           []UIFamilyMember    `json:"members"`
	Tasks             []UIFamilyTask      `json:"tasks"`
}

// UIFamilyMember Family member
type UIFamilyMember struct {
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"firstName"`
	LastName  string              `json:"lastName"`
	Role      ApiFamilyRole       `json:"role"`
}

// UIFamilyTask defines model for UIFamilyTask.
type UIFamilyTask struct {
	Description *string  `json:"description,omitempty"`
	Id          string   `json:"id"`
	MemberIds   []string `json:"memberIds"`
	Title       string   `json:"title"`
}

// UIUserInfo User Info
type UIUserInfo struct {
	Email             openapi_types.Email `json:"email"`
	FamilyDisplayName string              `json:"familyDisplayName"`
	FamilyUri         string              `json:"familyUri"`
	FirstName         *string             `json:"firstName,omitempty"`
	LastName          *string             `json:"lastName,omitempty"`
}

// GetStatsParams defines parameters for GetStats.
type GetStatsParams struct {
	// From From date
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To To date
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// CreateFamilyTaskJSONRequestBody defines body for CreateFamilyTask for application/json ContentType.
type CreateFamilyTaskJSONRequestBody = ApiCreateFamilyTaskCommandArgs

// DeleteFamilyTaskJSONRequestBody defines body for DeleteFamilyTask for application/json ContentType.
type DeleteFamilyTaskJSONRequestBody = ApiDeleteFamilyTaskCommandArgs

// UpdateFamilyTaskJSONRequestBody defines body for UpdateFamilyTask for application/json ContentType.
type UpdateFamilyTaskJSONRequestBody = ApiUpdateFamilyTaskCommandArgs

// UpdateTaskStatusJSONRequestBody defines body for UpdateTaskStatus for application/json ContentType.
type UpdateTaskStatusJSONRequestBody = ApiUpdateTaskStatusCommandArgs

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/commands/create-family-task)
	CreateFamilyTask(w http.ResponseWriter, r *http.Request)

	// (POST /api/commands/delete-family-task)
	DeleteFamilyTask(w http.ResponseWriter, r *http.Request)

	// (POST /api/commands/update-family-task)
	UpdateFamilyTask(w http.ResponseWriter, r *http.Request)

	// (POST /api/commands/update-task-status)
	UpdateTaskStatus(w http.ResponseWriter, r *http.Request)

	// (GET /api/stats)
	GetStats(w http.ResponseWriter, r *http.Request, params GetStatsParams)

	// (GET /api/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request)

	// (GET /api/ui/familyInfo)
	GetFamilyInfo(w http.ResponseWriter, r *http.Request)

	// (GET /api/ui/userInfo)
	GetUserInfo(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateFamilyTask operation middleware
func (siw *ServerInterfaceWrapper) CreateFamilyTask(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFamilyTask(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteFamilyTask operation middleware
func (siw *ServerInterfaceWrapper) DeleteFamilyTask(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFamilyTask(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateFamilyTask operation middleware
func (siw *ServerInterfaceWrapper) UpdateFamilyTask(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateFamilyTask(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateTaskStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateTaskStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTaskStatus(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStatsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetFamilyInfo operation middleware
func (siw *ServerInterfaceWrapper) GetFamilyInfo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFamilyInfo(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetUserInfo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserInfo(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/api/commands/create-family-task", wrapper.CreateFamilyTask).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/commands/delete-family-task", wrapper.DeleteFamilyTask).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/commands/update-family-task", wrapper.UpdateFamilyTask).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/commands/update-task-status", wrapper.UpdateTaskStatus).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/stats", wrapper.GetStats).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/tasks", wrapper.ListTasks).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/ui/familyInfo", wrapper.GetFamilyInfo).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/ui/userInfo", wrapper.GetUserInfo).Methods("GET")

	return r
}

type CreateFamilyTaskRequestObject struct {
	Body *CreateFamilyTaskJSONRequestBody
}

type CreateFamilyTaskResponseObject interface {
	VisitCreateFamilyTaskResponse(w http.ResponseWriter) error
}

type CreateFamilyTask200Response struct {
}

func (response CreateFamilyTask200Response) VisitCreateFamilyTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteFamilyTaskRequestObject struct {
	Body *DeleteFamilyTaskJSONRequestBody
}

type DeleteFamilyTaskResponseObject interface {
	VisitDeleteFamilyTaskResponse(w http.ResponseWriter) error
}

type DeleteFamilyTask200Response struct {
}

func (response DeleteFamilyTask200Response) VisitDeleteFamilyTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateFamilyTaskRequestObject struct {
	Body *UpdateFamilyTaskJSONRequestBody
}

type UpdateFamilyTaskResponseObject interface {
	VisitUpdateFamilyTaskResponse(w http.ResponseWriter) error
}

type UpdateFamilyTask200Response struct {
}

func (response UpdateFamilyTask200Response) VisitUpdateFamilyTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateTaskStatusRequestObject struct {
	Body *UpdateTaskStatusJSONRequestBody
}

type UpdateTaskStatusResponseObject interface {
	VisitUpdateTaskStatusResponse(w http.ResponseWriter) error
}

type UpdateTaskStatus200Response struct {
}

func (response UpdateTaskStatus200Response) VisitUpdateTaskStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetStatsRequestObject struct {
	Params GetStatsParams
}

type GetStatsResponseObject interface {
	VisitGetStatsResponse(w http.ResponseWriter) error
}

type GetStats200JSONResponse []ApiTaskStats

func (response GetStats200JSONResponse) VisitGetStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTasksRequestObject struct {
}

type ListTasksResponseObject interface {
	VisitListTasksResponse(w http.ResponseWriter) error
}

type ListTasks200JSONResponse []ApiTask

func (response ListTasks200JSONResponse) VisitListTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFamilyInfoRequestObject struct {
}

type GetFamilyInfoResponseObject interface {
	VisitGetFamilyInfoResponse(w http.ResponseWriter) error
}

type GetFamilyInfo200JSONResponse UIFamilyInfo

func (response GetFamilyInfo200JSONResponse) VisitGetFamilyInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserInfoRequestObject struct {
}

type GetUserInfoResponseObject interface {
	VisitGetUserInfoResponse(w http.ResponseWriter) error
}

type GetUserInfo200JSONResponse UIUserInfo

func (response GetUserInfo200JSONResponse) VisitGetUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/commands/create-family-task)
	CreateFamilyTask(ctx context.Context, request CreateFamilyTaskRequestObject) (CreateFamilyTaskResponseObject, error)

	// (POST /api/commands/delete-family-task)
	DeleteFamilyTask(ctx context.Context, request DeleteFamilyTaskRequestObject) (DeleteFamilyTaskResponseObject, error)

	// (POST /api/commands/update-family-task)
	UpdateFamilyTask(ctx context.Context, request UpdateFamilyTaskRequestObject) (UpdateFamilyTaskResponseObject, error)

	// (POST /api/commands/update-task-status)
	UpdateTaskStatus(ctx context.Context, request UpdateTaskStatusRequestObject) (UpdateTaskStatusResponseObject, error)

	// (GET /api/stats)
	GetStats(ctx context.Context, request GetStatsRequestObject) (GetStatsResponseObject, error)

	// (GET /api/tasks)
	ListTasks(ctx context.Context, request ListTasksRequestObject) (ListTasksResponseObject, error)

	// (GET /api/ui/familyInfo)
	GetFamilyInfo(ctx context.Context, request GetFamilyInfoRequestObject) (GetFamilyInfoResponseObject, error)

	// (GET /api/ui/userInfo)
	GetUserInfo(ctx context.Context, request GetUserInfoRequestObject) (GetUserInfoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateFamilyTask operation middleware
func (sh *strictHandler) CreateFamilyTask(w http.ResponseWriter, r *http.Request) {
	var request CreateFamilyTaskRequestObject

	var body CreateFamilyTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateFamilyTask(ctx, request.(CreateFamilyTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateFamilyTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateFamilyTaskResponseObject); ok {
		if err := validResponse.VisitCreateFamilyTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFamilyTask operation middleware
func (sh *strictHandler) DeleteFamilyTask(w http.ResponseWriter, r *http.Request) {
	var request DeleteFamilyTaskRequestObject

	var body DeleteFamilyTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFamilyTask(ctx, request.(DeleteFamilyTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFamilyTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFamilyTaskResponseObject); ok {
		if err := validResponse.VisitDeleteFamilyTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateFamilyTask operation middleware
func (sh *strictHandler) UpdateFamilyTask(w http.ResponseWriter, r *http.Request) {
	var request UpdateFamilyTaskRequestObject

	var body UpdateFamilyTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateFamilyTask(ctx, request.(UpdateFamilyTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateFamilyTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateFamilyTaskResponseObject); ok {
		if err := validResponse.VisitUpdateFamilyTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTaskStatus operation middleware
func (sh *strictHandler) UpdateTaskStatus(w http.ResponseWriter, r *http.Request) {
	var request UpdateTaskStatusRequestObject

	var body UpdateTaskStatusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTaskStatus(ctx, request.(UpdateTaskStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTaskStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTaskStatusResponseObject); ok {
		if err := validResponse.VisitUpdateTaskStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStats operation middleware
func (sh *strictHandler) GetStats(w http.ResponseWriter, r *http.Request, params GetStatsParams) {
	var request GetStatsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStats(ctx, request.(GetStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatsResponseObject); ok {
		if err := validResponse.VisitGetStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTasks operation middleware
func (sh *strictHandler) ListTasks(w http.ResponseWriter, r *http.Request) {
	var request ListTasksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTasks(ctx, request.(ListTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTasks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTasksResponseObject); ok {
		if err := validResponse.VisitListTasksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFamilyInfo operation middleware
func (sh *strictHandler) GetFamilyInfo(w http.ResponseWriter, r *http.Request) {
	var request GetFamilyInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFamilyInfo(ctx, request.(GetFamilyInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFamilyInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFamilyInfoResponseObject); ok {
		if err := validResponse.VisitGetFamilyInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserInfo operation middleware
func (sh *strictHandler) GetUserInfo(w http.ResponseWriter, r *http.Request) {
	var request GetUserInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserInfo(ctx, request.(GetUserInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserInfoResponseObject); ok {
		if err := validResponse.VisitGetUserInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXS2/buBP/KgL//6NSZ3dvvmWT3ULovrCpT0EOjDh22IgiS44KGIG++2JIyXrRiuzW",
	"RU+JKXIev3n95pXlWhldQomOrV+Zy59Bcf/vjZG3FjjC71zJYv+Ru5dbrRQvxY3d+RvGagMWJfhfyN0L",
	"/f2/hS1bs/+tOsmrRuzqxshOGqvrlFn4XEkLgq0fgoTHlOHeAFsz/fQJcmR1SqbcQQEnmZIJ/18Q5dDK",
	"chdVmIljKoOyf3UBJAnKStEbLpQsWcoUqCewvbetjt7bjw0kQ+sEuNxKg1KXERNbyZnwlyWCctFrzQG3",
	"lu/9b4nB0nmfpWDt3b6qIxi0HgxsZv40PdEtUcEdR2/hVlvFka2Z4AhXKBXZMnmw1fa0B1JEFTvkWLkF",
	"qUlu3YfLZ+LZx+CguPNkBmTSG8lkoUugz+5WVyX2rJElwg7sWTihRl68JbVylBhv+99qP7xIx0ZPFb6B",
	"QwhWW3DaQNkIZSl7KnT+AqRFWgsFfOEDeYMi3Bjxo7SvYErn4KwpuVYKBnH5iqI4N/tPa6FpLw8ajTEk",
	"NlnALyu3etpWwrdE0sdxd/Ft9zfFZTFwHfxJrHl4WXfSmYLv/+IK4mj6WxsrZxrxsA3Pgdh692cYDbEe",
	"TTVwsryQbWNp4zo8uJL2wYoh0XnWWjQXq8abY9Fq5uA4XnBCqKR1eDREBZ/5aJvhvKho/SQfw9Za1RnR",
	"U9komEPnvBF/ZFL9MJN/k22omUerlL4kWaxG4fuW59l5cywFIoXSWTCFieTIBqImBOz+2fDygxQuufkn",
	"Yyn7AtYF2K7f/URm0TTjRrI1++UdHaXMcHz28K24kZTANBjcKvfc+yoYcNVOJ6MdTkMSeHrSVGTDzigy",
	"nC5QG2djKs8CBuDwVy32YeqU2Ewdbkwhc/949cmFHA7ltKDY5paGug7gO6NLF5Lm5+vrqUN/f/BRQk7j",
	"8YE5QvVFUrLS8RAo4TeDZUCFLWIWqPGicTmg5laaSwBVeQ6yDKjAV2aBGrOrywE1x+MuCBQhdNXRp1mg",
	"yKzkvuX7MaB69OrCQMVZ5jcEyrW7yg4wvhwmdEU6lPkUjveAYdmh1me5AvQc62HCL6xWiQiUUtLB5wrs",
	"nqWs9F2dba1WxDYP4Czhw3U6MVfPKUF9uorHOMyLg7yIGw7Wxik3rNPTw3ogp9GwFtKhT/NpRP+QDtsv",
	"383zb+R0JVfbwUoSdf49YOLA0ShPtoMtZZLbvQXnK9FYshp4PW97vsmGLlc9dnfU4ULvdiASWSZ0/ajD",
	"B6Z4UXcPWpY62x28tsU8JGf1Y/1fAAAA//+9ipyi/hQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
