openapi: 3.0.1
info:
  title: ShpanKids API
  version: "0.1"
tags:
  - name: ShpanKids API
paths:
  /api/ui/userInfo:
    get:
      tags:
        - UI
      description: Get logged in user info
      operationId: getUserInfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UIUserInfo'

  /api/ui/familyInfo:
    get:
      tags:
        - UI
      description: Get session family info
      operationId: getFamilyInfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UIFamilyInfo'

  /api/commands/updateTaskStatus:
    post:
      tags:
        - shpankids
      description: Update Task Status
      operationId: updateTaskStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiUpdateTaskStatusCommandArgs'
      responses:
        '200':
          description: OK


  /api/tasks:
    get:
      tags:
        - shpankids
      description: list Tasks
      operationId: listTasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiTask'


components:
  schemas:
    UIUserInfo:
      type: object
      description: User Info
      required:
        - email
        - familyDisplayName
        - familyUri
      properties:
        email:
          type: string
          format: email
        familyDisplayName:
          type: string
        familyUri:
          type: string
        firstName:
          type: string
        lastName:
          type: string

    UIFamilyInfo:
      type: object
      description: Family info
      required:
        - familyUri
        - adminEmail
        - familyDisplayName
        - members
        - tasks
      properties:
        adminEmail:
          type: string
          format: email
        familyUri:
          type: string
        familyDisplayName:
          type: string
        members:
          type: array
          items:
            $ref: '#/components/schemas/UIFamilyMember'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/UIFamilyTask'

    UIFamilyTask:
      type: object
      required:
        - id
        - title
        - memberIds
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        memberIds:
          type: array
          items:
            type: string


    UIFamilyMember:
      type: object
      description: Family member
      required:
        - email
        - firstName
        - lastName
        - role
      properties:
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        role:
          $ref: '#/components/schemas/ApiFamilyRole'

    ApiFamilyRole:
      type: string
      enum:
        - admin
        - member
    ApiTask:
      type: object
      description: Task
      required:
        - id
        - title
        - description
        - status
        - forDate
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        forDate:
          type: string
          format: date-time
        dueDate:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/ApiTaskStatus'

    ApiTaskStatus:
      type: string
      enum:
        - open
        - done
        - blocked
        - irrelevant


    ApiUpdateTaskStatusCommandArgs:
      type: object
      required:
        - taskId
        - forDate
        - status
      properties:
        taskId:
          type: string
        forDate:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/ApiTaskStatus'
        comment:
          type: string
